### ISSUE TITLE
New ExaGear script

### ISSUE THREAD

**Issue by Crilum** [ShadityOS/ShadityOS#8]
I have an install/uninstall script for exagear, you can check it out in Pi-Apps issue #1051, or this is the Pi-Apps script: [Exagear](https://github.com/Botspot/pi-apps/files/7367008/ExaGear_with_some_bug_fixes.zip). If you like, you can use it for ShadityOS, just credit me :)

Also, where is the source?

**Comment by ShadityZ** [comment]
You can find the source for the current script [here](https://github.com/ShadityOS/exagear-rpi)

Your script looks interesting! Could you make a pull request in the repository? I could add the new script to patch v1.0.2

**Comment by Crilum** [comment]
I'll make a PR. :+1:

**Comment by Crilum** [comment]
Actually, is there any reason why the current script doesn't work?

**Comment by Crilum** [comment]
It looks really similar.

**Comment by ShadityZ** [comment]
Thanks for reminding me! I needed to update the README. The script was patched in v1.0.1. The reason for this was because of [this](https://github.com/ShadityOS/ShadityOS/issues/2) issue that won't let the tilda symbol expand into the $HOME path. This means several commands fail. In fact, I may have to edit your script to make sure that issue doesn't get in the way. If you have any ideas on how to fix the problem, please do mention them.

**Comment by ShadityZ** [comment]
Request has been merged, closing issue now...

**Comment by ShadityZ** [comment]
NOTE: This is an old issue, people reading this should be informed that the ```exagear-rpi``` repository has been merged with this one. You can now find the ```install-exagear.sh``` merged [here](https://github.com/ShadityOS/ShadityOS/blob/master/scripts/install-exagear.sh)
